// Recipe 33: Micro-Learning Grid — Generate a mini-textbook from a single subject.
//
// This recipe demonstrates a complex multi-step pipeline on the grid:
// 1. Planning: Ask a high-reasoning model for a 5-part textbook outline.
// 2. Decomposition: Split the outline into independent writing tasks.
// 3. Parallel Execution: Dispatch all 5 parts to the grid simultaneously.
// 4. Synthesis: Combine the parts into a final Markdown textbook.
//
// Usage:
//   go run learning.go "Gradient Descent"
//   go run learning.go --hub http://localhost:9000 "Quantum Computing"
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
	"gopkg.in/yaml.v3"
)

const planningSystem = "You are an expert curriculum designer. Given a subject, create a 5-part outline for a micro-textbook. " +
	"Each part must have a 'title' and a 'description' of what to cover. Return ONLY valid JSON: [{\"title\": \"...\", \"description\": \"...\"}, ...]"

const writingSystem = "You are a professional technical educator. Write one chapter of a micro-textbook. " +
	"Be clear, use Markdown, include examples, and keep it engaging. Do not include a preamble or postamble."

type chapterOutline struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

type chapterResult struct {
	Title   string
	Content string
	Error   string
}

func defaultHubURL() string {
	home, _ := os.UserHomeDir()
	data, err := os.ReadFile(filepath.Join(home, ".igrid", "config.yaml"))
	if err != nil {
		return "http://localhost:9000"
	}
	var cfg struct {
		Hub struct {
			URLs []string `yaml:"urls"`
		} `yaml:"hub"`
	}
	yaml.Unmarshal(data, &cfg)
	if len(cfg.Hub.URLs) > 0 {
		return strings.TrimRight(cfg.Hub.URLs[0], "/")
	}
	return "http://localhost:9000"
}

func main() {
	hubURL := flag.String("hub", defaultHubURL(), "Hub URL")
	model := flag.String("model", "llama3", "Model to use for all steps")
	flag.Parse()

	subject := flag.Arg(0)
	if subject == "" {
		fmt.Println("Usage: go run learning.go <subject>")
		return
	}

	fmt.Printf("\n🎓 Micro-Learning Grid: \"%s\"\n", subject)
	fmt.Printf("   Hub: %s\n\n", *hubURL)

	// Step 1: Planning
	fmt.Print("   [1/3] Planning curriculum... ")
	outlineJSON, _, err := submitAndWait(*hubURL, planningSystem, "Subject: "+subject, *model)
	if err != nil {
		fmt.Printf("FAILED: %v\n", err)
		return
	}
	var outline []chapterOutline
	// Clean up potential markdown code blocks from LLM
	jsonStr := strings.TrimSpace(outlineJSON)
	jsonStr = strings.TrimPrefix(jsonStr, "```json")
	jsonStr = strings.TrimPrefix(jsonStr, "```")
	jsonStr = strings.TrimSuffix(jsonStr, "```")
	if err := json.Unmarshal([]byte(jsonStr), &outline); err != nil {
		fmt.Printf("FAILED to parse outline: %v\n", err)
		fmt.Println("Raw response:", outlineJSON)
		return
	}
	fmt.Printf("done (%d chapters)\n", len(outline))

	// Step 2: Parallel Writing
	fmt.Printf("   [2/3] Generating chapters in parallel...\n")
	var wg sync.WaitGroup
	results := make([]chapterResult, len(outline))
	for i, ch := range outline {
		wg.Add(1)
		go func(idx int, c chapterOutline) {
			defer wg.Done()
			prompt := fmt.Sprintf("Subject: %s\nChapter: %s\nFocus: %s", subject, c.Title, c.Description)
			content, _, err := submitAndWait(*hubURL, writingSystem, prompt, *model)
			if err != nil {
				results[idx] = chapterResult{Title: c.Title, Error: err.Error()}
				fmt.Printf("         ! Chapter %d FAILED: %v\n", idx+1, err)
			} else {
				results[idx] = chapterResult{Title: c.Title, Content: content}
				fmt.Printf("         ✓ Chapter %d complete: %s\n", idx+1, c.Title)
			}
		}(i, ch)
	}
	wg.Wait()

	// Step 3: Synthesis
	fmt.Printf("\n   [3/3] Synthesizing textbook...\n")
	var textbook bytes.Buffer
	textbook.WriteString(fmt.Sprintf("# %s: A Micro-Textbook\n\n", subject))
	textbook.WriteString("Generated by Momagrid Decentralized AI Grid\n\n---\n\n")

	for i, res := range results {
		textbook.WriteString(fmt.Sprintf("## Chapter %d: %s\n\n", i+1, res.Title))
		if res.Error != "" {
			textbook.WriteString(fmt.Sprintf("> *Error generating this chapter: %s*\n\n", res.Error))
		} else {
			textbook.WriteString(res.Content)
			textbook.WriteString("\n\n")
		}
		textbook.WriteString("---\n\n")
	}

	outPath := fmt.Sprintf("micro_textbook_%s.md", strings.ToLower(strings.ReplaceAll(subject, " ", "_")))
	os.WriteFile(outPath, textbook.Bytes(), 0644)
	fmt.Printf("\n✨ Success! Your mini-textbook is ready: %s\n", outPath)
}

func submitAndWait(hub, system, prompt, model string) (string, int, error) {
	taskID := "learn-" + uuid.New().String()[:8]
	payload := map[string]interface{}{
		"task_id":    taskID,
		"model":      model,
		"prompt":     prompt,
		"system":     system,
		"max_tokens": 2048,
	}
	b, _ := json.Marshal(payload)
	resp, err := http.Post(hub+"/tasks", "application/json", bytes.NewReader(b))
	if err != nil {
		return "", 0, err
	}
	resp.Body.Close()

	for i := 0; i < 100; i++ {
		r, err := http.Get(fmt.Sprintf("%s/tasks/%s", hub, taskID))
		if err != nil {
			time.Sleep(2 * time.Second)
			continue
		}
		var data map[string]interface{}
		json.NewDecoder(r.Body).Decode(&data)
		r.Body.Close()

		if data["state"] == "COMPLETE" {
			res := data["result"].(map[string]interface{})
			return res["content"].(string), int(res["output_tokens"].(float64)), nil
		}
		if data["state"] == "FAILED" {
			return "", 0, fmt.Errorf("task failed")
		}
		time.Sleep(2 * time.Second)
	}
	return "", 0, fmt.Errorf("timeout")
}
